### ISSUE TITLE
Steps for Execution of Project

### ISSUE THREAD

**Issue by chandu0211** [alitourani/vehicle-speed-measurement#4]
Hello Sir,
Could you please add a text file with detail steps explaining how to execute the project without any error. I'm am not quite familiar with OpenCV and it's libraries. So could you please provide some guidance in executing this project in my computer.
 Thanks in advance.

**Comment by alitourani** [comment]
Hi @chandu0211 
You can simply clone the project and install the required packages by Nuget Package Manager. I've added some explanations on README.md file.
